### ISSUE TITLE
Asigning R_SEGID and A_SEGID to an address point

### ISSUE THREAD

**Issue by northrivergeo** [northrivergeo/tn_ng911_data_model#1]
R_SEGID is for Routing 
A_SEGID is for Access 

Right now in the data model there is no "connector" between the address point and the centerline. So that must be manually entered and not assigned through a menu. I don't know if it would be possible to set up a way to select the road and then "assign" it as access, routing, or both in QGIS.

**Comment by rjhale1971** [comment]
I'm adding one more layer to this. You add a point for "access" (A_SEGID) and one for "routing" (R-SEGID) and from that you assign the right street segment and you should be able to derive an address.
