### ISSUE TITLE
City Trigger Function (Carried from Issue #23)

### ISSUE THREAD

**Issue by KSnyderCode** [northrivergeo/tn_ng911_data_model#27]
I checked the TN 911 Standard. The city can't be assigned from the Census. That has to be assigned based off the local county MSAG layer. I can write a quick trigger for that, but that's likely just has to be a placeholder for now.

**Comment by northrivergeo** [comment]
Hah - so I talked to chad - they can't pull the city from census - so it's sorta eyeballed.
